### ISSUE TITLE
Для чего в твоей реализации redux?

### ISSUE THREAD

**Issue by blmzv** [Wriklend/sortedTable#5]
То, что используется redux — хорошо.
Но в твоей реализации не вижу ни какой пользы от него.

**Comment by Wriklend** [comment]
Redux был указан в тз. Действительно, в моей реализации пользы от него нет. 
Если нужно убрать - уберу.
Если есть красивое решение с использованием этого инструмента - буду рад о нем узнать.
Пока оставил.

**Comment by blmzv** [comment]
Для твоей реализации я бы вынес логику сортировки в reducer, например.

**Comment by Wriklend** [comment]
Согласен, но какой смысл сортировать стор? Эти данные могут использоваться в другой таблице, например. Не переделал, т.к. слишком много логики пришлось бы менять. Время:(

**Comment by blmzv** [comment]
> Эти данные могут использоваться в другой таблице, например.
ok
